netflix:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: QNYXTZC-MK52769
      user: dbt
      password: dbtPassword123
      role: TRANSFORM
      database: MOVIELENS
      warehouse: COMPUTE_WH
      schema: dev
      threads: 1
      client_session_keep_alive: False
